"""Remove agent locations and route comparison columns

Revision ID: 3d6e8b730c7c
Revises: 226390c72a60
Create Date: 2026-07-15 18:35:22.354368

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3d6e8b730c7c'
down_revision: Union[str, Sequence[str], None] = '226390c72a60'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_agent_locations_id'), table_name='agent_locations')
    op.drop_table('agent_locations')
    op.drop_column('routes', 'original_total_distance_meters')
    op.drop_column('routes', 'optimized_total_distance_meters')
    op.drop_column('routes', 'optimized_total_duration_seconds')
    op.drop_column('routes', 'original_total_duration_seconds')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('routes', sa.Column('original_total_duration_seconds', sa.INTEGER(), nullable=False))
    op.add_column('routes', sa.Column('optimized_total_duration_seconds', sa.INTEGER(), nullable=False))
    op.add_column('routes', sa.Column('optimized_total_distance_meters', sa.INTEGER(), nullable=False))
    op.add_column('routes', sa.Column('original_total_distance_meters', sa.INTEGER(), nullable=False))
    op.create_table('agent_locations',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('delivery_agent_id', sa.INTEGER(), nullable=False),
    sa.Column('latitude', sa.NUMERIC(precision=10, scale=8), nullable=False),
    sa.Column('longitude', sa.NUMERIC(precision=11, scale=8), nullable=False),
    sa.Column('recorded_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['delivery_agent_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_agent_locations_id'), 'agent_locations', ['id'], unique=False)
    # ### end Alembic commands ###
